Adding my repo file
GSSoC24/Hack-Web3Conf pull request #364
Opened 2024-11-06 17:44 UTC by puneeth072003

Adding the files

2024-11-06 17:46 UTC, Snehsk requested changes
Hi could you please remove this image and add only dashboard page here.

Please rename the screenshot as this format 

> Name-projectname-date

2024-11-06 18:59 UTC, puneeth072003 commented
@Snehsk Sorry for the inconvenience

2024-11-07 04:40 UTC, Snehsk approved these changes

2024-11-07 04:40 UTC, merged

2024-11-07 04:41 UTC, Snehsk reviewed
🚀 Congratulations for your submission, your points will be reflected in the leaderboard till night.